version: '3.8'

services:
  c_orderDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1
    ports:
      - "1433:1433"
    container_name: c_orderDB
    hostname: localhost
    platform: linux/amd64
    restart: always
    volumes:
      - mssql_volume:/var/opt/mssql
        

volumes: 
  mssql_volume: {}
